spring:
  profiles:
    active: "prod"
    include: "common"

---

spring:
  config:
    activate:
      on-profile: "common"
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/santanderdb
    # url: jdbc:postgresql://127.0.0.1:5432/santanderdb    # Linux
